window.DRAGONS = [
  // Starter
  {
    id: "ember",
    name: "Ember",
    emoji: "🐲",
    rarity: "Starter",
    theme: "Starter",
    weight: 0,
    blurb:
      "Your first friendly dragon, always glowing with a warm little flame.",
  },

  // Forest
  {
    id: "mosswing",
    name: "Mosswing",
    emoji: "🦎",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "A leafy little lizard-dragon that naps in sunny ferns.",
  },
  {
    id: "sparklepaw",
    name: "Sparklepaw",
    emoji: "🦊",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "A curious fox-dragon with glittering paws and a bushy tail.",
  },
  {
    id: "acornflare",
    name: "Acornflare",
    emoji: "🐿️",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "This tree-top dragon stores shiny acorns in hidden nests.",
  },
  {
    id: "thistletail",
    name: "Thistletail",
    emoji: "🐱",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "Soft paws, sharp brain, and a fluffy dragon tail.",
  },
  {
    id: "fernfizz",
    name: "Fernfizz",
    emoji: "🦔",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "A hedgehog hatchling with sparkling fern-coloured spines.",
  },
  {
    id: "cinderchip",
    name: "Cinderchip",
    emoji: "🐭",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "Tiny, cheeky, and always hiding glowing pebbles.",
  },
  {
    id: "mistymaple",
    name: "MistyMaple",
    emoji: "🦌",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "This gentle forest dragon drifts through misty mornings.",
  },
  {
    id: "pebblepop",
    name: "Pebblepop",
    emoji: "🐨",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "It naps often in treetops and snores little puffs of smoke.",
  },
  {
    id: "lilyglow",
    name: "Lilyglow",
    emoji: "🐰",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "A meadow hopper with glowing whiskers.",
  },
  {
    id: "blossomblink",
    name: "Blossomblink",
    emoji: "🐣",
    rarity: "Common",
    theme: "Forest",
    weight: 8,
    blurb: "A chirpy hatchling with spring petals on its wings.",
  },
  {
    id: "marblesnout",
    name: "Marblesnout",
    emoji: "🐗",
    rarity: "Uncommon",
    theme: "Forest",
    weight: 5,
    blurb: "Strong, stubborn, and always snuffling through ancient roots.",
  },
  {
    id: "nettlenose",
    name: "Nettlenose",
    emoji: "🦝",
    rarity: "Uncommon",
    theme: "Forest",
    weight: 5,
    blurb: "A clever collector of shiny pebbles and moonlit treasures.",
  },
  {
    id: "tangletooth",
    name: "Tangletooth",
    emoji: "🐊",
    rarity: "Uncommon",
    theme: "Forest",
    weight: 5,
    blurb: "This swampy snapper has a surprisingly gentle roar.",
  },

  // Water
  {
    id: "bubblesnout",
    name: "Bubblesnout",
    emoji: "🐢",
    rarity: "Common",
    theme: "Water",
    weight: 8,
    blurb: "Slow, steady, and happiest paddling through lily ponds.",
  },
  {
    id: "puddlespark",
    name: "Puddlespark",
    emoji: "🐸",
    rarity: "Common",
    theme: "Water",
    weight: 8,
    blurb: "It loves hopping through puddles and splashing tiny sparks.",
  },
  {
    id: "ripplewing",
    name: "Ripplewing",
    emoji: "🐟",
    rarity: "Common",
    theme: "Water",
    weight: 8,
    blurb: "It darts through streams leaving bright ripples behind.",
  },
  {
    id: "drizzlehop",
    name: "Drizzlehop",
    emoji: "🦆",
    rarity: "Common",
    theme: "Water",
    weight: 8,
    blurb: "A rainy-day dragon that splashes through silver puddles.",
  },
  {
    id: "copperclaw",
    name: "Copperclaw",
    emoji: "🦀",
    rarity: "Uncommon",
    theme: "Water",
    weight: 5,
    blurb: "Side-steps over rocky shores with surprising speed.",
  },
  {
    id: "rainwhistle",
    name: "Rainwhistle",
    emoji: "🐬",
    rarity: "Uncommon",
    theme: "Water",
    weight: 5,
    blurb: "A wave-riding dragon that sings to the sea breeze.",
  },
  {
    id: "glowripple",
    name: "Glowripple",
    emoji: "🦦",
    rarity: "Uncommon",
    theme: "Water",
    weight: 5,
    blurb: "A river dragon that giggles in glowing bubbles.",
  },
  {
    id: "starfin",
    name: "Starfin",
    emoji: "🐙",
    rarity: "Rare",
    theme: "Water",
    weight: 3,
    blurb: "A deep-sea dragon with eight glowing, starry arms.",
  },
  {
    id: "mirrormist",
    name: "Mirrormist",
    emoji: "🦢",
    rarity: "Rare",
    theme: "Water",
    weight: 3,
    blurb: "It glides across silver lakes leaving glowing mist behind.",
  },
  {
    id: "silversnap",
    name: "Silversnap",
    emoji: "🦈",
    rarity: "Rare",
    theme: "Water",
    weight: 3,
    blurb: "This sharp swimmer cuts through moonlit waves.",
  },

  // Sky
  {
    id: "flutterflame",
    name: "Flutterflame",
    emoji: "🦋",
    rarity: "Common",
    theme: "Sky",
    weight: 8,
    blurb: "A bright bug-dragon hybrid with twinkling wings.",
  },
  {
    id: "honeydash",
    name: "Honeydash",
    emoji: "🐝",
    rarity: "Common",
    theme: "Sky",
    weight: 8,
    blurb: "A buzzy little flyer that zips between wildflowers.",
  },
  {
    id: "cometcrumb",
    name: "Cometcrumb",
    emoji: "🐹",
    rarity: "Common",
    theme: "Sky",
    weight: 8,
    blurb: "Fast as a shooting star and always chasing moon crumbs.",
  },
  {
    id: "cloudhorn",
    name: "Cloudhorn",
    emoji: "🦄",
    rarity: "Uncommon",
    theme: "Sky",
    weight: 5,
    blurb: "A proud sky creature that gallops across soft clouds.",
  },
  {
    id: "breezebyte",
    name: "Breezebyte",
    emoji: "🕊️",
    rarity: "Uncommon",
    theme: "Sky",
    weight: 5,
    blurb: "A cloud-soft dragon that drifts on the gentlest winds.",
  },
  {
    id: "sunburst",
    name: "Sunburst",
    emoji: "☀️",
    rarity: "Rare",
    theme: "Sky",
    weight: 3,
    blurb: "A glowing spirit-dragon wrapped in golden rays.",
  },
  {
    id: "auroratail",
    name: "Auroratail",
    emoji: "🦚",
    rarity: "Rare",
    theme: "Sky",
    weight: 3,
    blurb: "Northern lights shimmer all along its tail feathers.",
  },
  {
    id: "thunderpebble",
    name: "Thunderpebble",
    emoji: "🦁",
    rarity: "Rare",
    theme: "Sky",
    weight: 3,
    blurb: "A tiny roaring storm trapped inside a brave little dragon.",
  },
  {
    id: "dreamdrift",
    name: "Dreamdrift",
    emoji: "🐋",
    rarity: "Rare",
    theme: "Sky",
    weight: 3,
    blurb: "A sky-whale dragon that floats through sleepy clouds.",
  },
  {
    id: "cometcrest",
    name: "Cometcrest",
    emoji: "🦅",
    rarity: "Epic",
    theme: "Sky",
    weight: 2,
    blurb: "A soaring legend with a star-bright crown.",
  },

  // Magic
  {
    id: "pebblechomp",
    name: "Pebblechomp",
    emoji: "🦖",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "A tiny dino-dragon with a mighty mountain roar.",
  },
  {
    id: "frostfeather",
    name: "Frostfeather",
    emoji: "🐧",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "A cool-headed creature with icy feathers and sparkling breath.",
  },
  {
    id: "saffronscale",
    name: "Saffronscale",
    emoji: "🐍",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "Its golden scales shimmer like sunlight on warm sand.",
  },
  {
    id: "duskdancer",
    name: "Duskdancer",
    emoji: "🦇",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "It flutters at twilight leaving trails of violet dust.",
  },
  {
    id: "shellspark",
    name: "Shellspark",
    emoji: "🐌",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "Slow, shiny, and trailing a little line of glitter.",
  },
  {
    id: "prismapaw",
    name: "Prismapaw",
    emoji: "🐼",
    rarity: "Uncommon",
    theme: "Magic",
    weight: 5,
    blurb: "Its paws sparkle with rainbow light beneath waterfalls.",
  },
  {
    id: "moonwhisker",
    name: "Moonwhisker",
    emoji: "🐺",
    rarity: "Rare",
    theme: "Magic",
    weight: 3,
    blurb: "A silent guardian that prowls beneath moonbeams and silver stars.",
  },
  {
    id: "velvetvolt",
    name: "Velvetvolt",
    emoji: "🐆",
    rarity: "Rare",
    theme: "Magic",
    weight: 3,
    blurb: "Silky soft and streaked with tiny flashes of lightning.",
  },
  {
    id: "midnightmoss",
    name: "Midnightmoss",
    emoji: "🐻",
    rarity: "Rare",
    theme: "Magic",
    weight: 3,
    blurb: "A sleepy cave guardian wrapped in moonlit moss.",
  },
  {
    id: "opalflare",
    name: "Opalflare",
    emoji: "🦋",
    rarity: "Epic",
    theme: "Magic",
    weight: 2,
    blurb: "Its wings sparkle with opal fire in the moonlight.",
  },
  {
    id: "shimmerfang",
    name: "Shimmerfang",
    emoji: "🐯",
    rarity: "Epic",
    theme: "Magic",
    weight: 2,
    blurb: "A striped hunter whose scales flash like jewels.",
  },
  {
    id: "runeblossom",
    name: "Runeblossom",
    emoji: "🦜",
    rarity: "Epic",
    theme: "Magic",
    weight: 2,
    blurb: "Ancient symbols glow across its petals and feathers.",
  },

  // Legendary
  {
    id: "stormscale",
    name: "Stormscale",
    emoji: "🐉",
    rarity: "Legendary",
    theme: "Legendary",
    weight: 1,
    blurb: "A legendary storm dragon wrapped in thunder and cloud.",
  },
  {
    id: "dawnkeeper",
    name: "Dawnkeeper",
    emoji: "🌅",
    rarity: "Legendary",
    theme: "Legendary",
    weight: 1,
    blurb: "It rises with the sun and guards the brightest treasures.",
  },
  {
    id: "voidglimmer",
    name: "Voidglimmer",
    emoji: "🌌",
    rarity: "Legendary",
    theme: "Legendary",
    weight: 1,
    blurb: "A cosmic dragon wrapped in stardust and midnight hush.",
  },
  {
    id: "crownflare",
    name: "Crownflare",
    emoji: "👑",
    rarity: "Legendary",
    theme: "Legendary",
    weight: 1,
    blurb: "A royal hatchling with a golden blaze and huge heart.",
  },
];
